(set-logic LIA)
(synth-fun fives ((x Int)) Int)
(synth-fun threes ((x Int)) Int)
(declare-var x Int)
(declare-var altfives Int)
(declare-var altthrees Int)
(constraint (<= 0 (threes x)))
(constraint (<= 0 (fives x)))
(constraint (or (<= x 14)
	        (and (= (+ (* 3 (threes x)) (* 5 (fives x))) x)
		     (or (and (and (<= 0 altthrees) (<= 0 altfives))
 	                      (= (+ (* 3 altthrees) (* 5 altfives)) x))
		         (<= (+ (threes x) (fives x)) (+ altthrees altfives))))))
(check-synth)
