(set-logic LIA)
(synth-fun w1 ((x Int)) Int)
(synth-fun w2 ((x Int)) Int)
(synth-fun w3 ((x Int)) Int)
(synth-fun w4 ((x Int)) Int)

(declare-var weight Int)
(constraint (or (< weight 0)
              (or (< 10 weight)
	        (and (= (+ (w1 weight) (+ (* 3 (w2 weight)) (+ (* 9 (w3 weight)) (* 27 (w4 weight))))) weight)
		     (and (and (<= -1 (w1 weight)) (<= (w1 weight) 1))
		       (and (and (<= -1 (w2 weight)) (<= (w2 weight) 1))
		         (and (and (<= -1 (w3 weight)) (<= (w3 weight) 1))
			   (and (<= -1 (w4 weight)) (<= (w4 weight) 1)))))))))
(check-synth)
