open BatPervasives
open Polynomial

  type rew_t = Rewrite.t

  (* Common monomial ordering *)
  let order = Monomial.degrevlex

  let add_saturate_r ideal p = Rewrite.add_saturate ideal p

  let reduce_r ideal p =
    Rewrite.reduce ideal p

  (* Projection of the ideal generated by a set of polynomials *)
  let project_impl p generators =
    let elim_order = Monomial.block [not % p] order in
    let rewrite =
      Rewrite.mk_rewrite elim_order generators
      |> Rewrite.grobner_basis
    in
    Rewrite.restrict
      (fun m ->
         BatEnum.for_all (fun (d, _) -> p d) (Monomial.enum m))
      rewrite

  let project_r p j = project_impl p (Rewrite.generators j)

  let mem_r p j = Rewrite.reduce_zero j p

  let subset_r = Rewrite.subset

  let equal_r = Rewrite.equal

  let make_r generators =
    Rewrite.grobner_basis (Rewrite.mk_rewrite order generators)

  let generators_r = Rewrite.generators


  let pp_r = Rewrite.pp

  let intersect_r j k =
    let j = generators_r j in
    let k = generators_r k in
    let t =
      1 + (List.fold_left
             (fun m p ->
                try max m (SrkUtil.Int.Set.max_elt (QQXs.dimensions p))
                with Not_found -> m)
             0
             (j @ k))
    in
    (* { tp : p in j } *)
    let j' = List.map (QQXs.mul (QQXs.of_dim t)) j in
    (* { (1-t)p : p in k } *)
    let k' =
      List.map (QQXs.mul (QQXs.sub (QQXs.scalar QQ.one) (QQXs.of_dim t))) k
    in
    project_impl (not % (=) t) (j' @ k')




  module IS = SrkUtil.Int.Set

  type fgb_t = 
  {
    basis : FGb.fpoly list
  ; vs : IS.t
  }

  (*type t = Rewrite.t*)
  (*open Rewrite

  (* Common monomial ordering *)
  let order = Monomial.degrevlex*)

  let to_fmon vs = 
    FGb.convert_to_faugere (BatList.of_enum (IS.enum vs))

  let of_fmon vs = 
    FGb.convert_from_faugere (BatList.of_enum (IS.enum vs))

  (*maybe a better way to do this*)
  let recompute_fmon old_vs new_vs p = 
    to_fmon new_vs (of_fmon old_vs p)

  let generators_f ideal = List.filter_map (fun p -> let pq = of_fmon ideal.vs p in if QQXs.is_zero pq then None else Some pq) ideal.basis


  let add_saturate_f ideal p = 
    if QQXs.is_zero p then ideal
    else
      let p_vs = QQXs.dimensions p in
      let gens, vs = 
        if IS.subset p_vs ideal.vs then
          let p_fmon = to_fmon ideal.vs p in
          p_fmon :: ideal.basis, ideal.vs
        else
          let new_vs = IS.union p_vs ideal.vs in
          let p_fmon = to_fmon new_vs p in
          p_fmon :: (List.map (recompute_fmon ideal.vs new_vs) ideal.basis), new_vs
      in
      let basis = FGb.grobner_basis_fmon (BatList.of_enum (IS.enum vs)) [] gens in
      {basis; vs}


  let mk_rewrite_f ideal = 
    let gens = List.map (of_fmon ideal.vs) ideal.basis in
    let order = FGb.get_mon_order (BatList.of_enum (IS.enum ideal.vs)) [] in
    Rewrite.mk_rewrite order gens


  let reduce_f ideal p =
    Rewrite.reduce (mk_rewrite_f ideal) p


  let project_f pred j = 
    let v_list = BatList.of_enum (IS.enum j.vs) in
    let _, (good_indices_r, bad_incicies_r) = List.fold_left (
      fun (i, (good, bad)) v ->
        if pred v then (i+1, (i :: good, bad))
        else (i+1,(good, i :: bad))
    ) (0, ([], [])) v_list in
    let good_i, bad_i = List.rev good_indices_r, List.rev bad_incicies_r in
    let rearrange_mon ml = 
      (List.map (fun i -> List.nth ml i) bad_i) @ (List.map (fun i -> List.nth ml i) good_i)
    in
    let rearrange_p = List.map (fun (c, ml) -> c, rearrange_mon ml) in
    let good_vs, bad_vs = List.partition pred v_list in
    let rearranged = List.map rearrange_p j.basis in
    let basis_with_bad = FGb.grobner_basis_fmon bad_vs good_vs rearranged in
    let mon_only_good (c, ml) = 
      let rec aux i  = 
        if i >= List.length bad_vs then true
        else 
          let deg = List.nth ml i in
          if deg = 0 then aux (i + 1)
          else false
      in
      ZZ.equal c ZZ.zero || (aux 0)
    in
    let basis_no_bad = List.filter (List.for_all mon_only_good) basis_with_bad in
    let shorten_mon (c, m) = 
      let m_i, _ = List.partition (fun (i, _) -> i >= List.length bad_vs) (List.mapi (fun i a -> i, a) m) in
      c, snd (List.split m_i)
    in
    let basis = List.map (List.map shorten_mon) basis_no_bad in
    {basis; vs = IS.of_list good_vs}

  let make_f generators =
    let vs = List.fold_left (fun acc p -> IS.union acc (QQXs.dimensions p)) IS.empty generators in
    let fpolys = List.map (to_fmon vs) generators in
    let basis = FGb.grobner_basis_fmon (BatList.of_enum (IS.enum vs)) [] fpolys in
    {basis; vs}

  let intersect_f j k =
    let vs = IS.union j.vs k.vs in
    let j = generators_f j in
    let k = generators_f k in
    let t = (IS.max_elt vs) + 1 in
    (* { tp : p in j } *)
    let j' = List.map (QQXs.mul (QQXs.of_dim t)) j in
    (* { (1-t)p : p in k } *)
    let k' =
      List.map (QQXs.mul (QQXs.sub (QQXs.scalar QQ.one) (QQXs.of_dim t))) k
    in
    let gens = List.map (to_fmon (IS.add t vs)) (j' @ k') in
    project_f (fun i -> i <> t) {basis = gens; vs = (IS.add t vs)}

  let pp_f pp_dim f i = 
    Rewrite.pp pp_dim f (mk_rewrite_f i)

  let mem_f p j = 
    let rw = mk_rewrite_f j in
    Rewrite.reduce_zero rw p

  let subset_f i j = 
    let rwi, rwj = mk_rewrite_f i, mk_rewrite_f j in
    Rewrite.subset rwi rwj

  let equal_f i j = 
    let rwi, rwj = mk_rewrite_f i, mk_rewrite_f j in
    Rewrite.equal rwi rwj


  type t = R of rew_t | F of fgb_t

  let pp pp_dim f i = 
    match i with | R id -> pp_r pp_dim f id | F id -> pp_f pp_dim f id


  let make gs = 
    if !FGb.use_fgb then F (make_f gs)
    else R (make_r gs)

  let add_saturate i p = 
    match i with | R id -> R (add_saturate_r id p) | F id -> F (add_saturate_f id p)

  let reduce i = 
    match i with | R id -> reduce_r id | F id -> reduce_f id

  
  let generators i = 
    match i with | R id -> generators_r id | F id -> generators_f id

  let subset i j = 
    match (i, j) with
    | R idi, R idj -> subset_r idi idj
    | F idi, F idj -> subset_f idi idj
    | _ -> failwith "Not handling different implementations"

  let equal i j = 
    match (i, j) with
    | R idi, R idj -> equal_r idi idj
    | F idi, F idj -> equal_f idi idj
    | _ -> failwith "Not handling different implementations"

  let mem p i = 
    match i with
    | R idi -> mem_r p idi
    | F idi -> mem_f p idi

  let intersect i j = 
    match (i, j) with
    | R idi, R idj -> R (intersect_r idi idj)
    | F idi, F idj -> F (intersect_f idi idj)
    | _ -> failwith "Not handling different implementations"

  let project f i = 
    match i with
    | R idi -> R (project_r f idi)
    | F idi -> F (project_f f idi)

  let mk_rewrite i = 
    match i with
    | R idi -> idi
    | F idi -> mk_rewrite_f idi

  let product j k =
    let j_generators = generators j in
    List.fold_left (fun gen p ->
        List.fold_left (fun gen q ->
            (QQXs.mul p q)::gen)
          gen
          j_generators)
      []
      (generators k)
    |> make

  let sum j k =
    List.fold_left (fun rewrite q ->
        add_saturate rewrite q)
      j
      (generators k)

