open Srk
open OUnit
open BatPervasives
open Test_pervasives

module V = Linear.QQVector

let mk_vector l = mk_vector (List.rev l)

let lattice_of vs = IntLattice.hermitize (IntLattice.of_generators vs)

let xy_lattice =
  lattice_of (List.map mk_vector [[0 ; 1] ; [1 ; 0]])

let empty_lattice = IntLattice.hermitize IntLattice.bottom

let lattice1 =
  (*
     [ 2 ; 4 ; 4 ; 5
       1 ; 2 ; 3 ; 4
       3 ; 6 ; 2 ; 1 ]
  -> [ 1 ; 2 ; 3 ; 4
       2 ; 4 ; 4 ; 5
       3 ; 6 ; 2 ; 1 ]
  -> [ 1 ; 2 ;  3 ;  4
       0 ; 0 ; -2 ; -3
       0 ; 0 ; -7 ; -11 ]
  -> [ 1 ; 2 ; 3 ; 4
       0 ; 0 ; 2 ; 3
       0 ; 0 ; 7 ; 11 ]
  -> [ 1 ; 2 ; 3 ; 4
       0 ; 0 ; 2 ; 3
       0 ; 0 ; 1 ; 2 ]
  -> [ 1 ; 2 ; 3 ; 4
       0 ; 0 ; 1 ; 2
       0 ; 0 ; 2 ; 3 ]
  -> [ 1 ; 2 ; 0 ; -2
       0 ; 0 ; 1 ;  2
       0 ; 0 ; 0 ; -1 ]
  -> [ 1 ; 2 ; 0 ; -2
       0 ; 0 ; 1 ;  2
       0 ; 0 ; 0 ;  1 ]
  -> [ 1 ; 2 ; 0 ; 0
       0 ; 0 ; 1 ; 0
       0 ; 0 ; 0 ; 1 ]
   *)
  let v1 = mk_vector [2 ; 4 ; 4 ; 5] in
  let v2 = mk_vector [1 ; 2 ; 3 ; 4] in
  let v3 = mk_vector [3 ; 6 ; 2 ; 1] in
  lattice_of [v1 ; v2 ; v3]

let lattice2 =
  (*
     [ 2 ; 1 ; 0 ; 0
       0 ; 1 ; 2 ; 0
     ]
  -> [ 2 ; 0 ; -2 ; 0
       0 ; 1 ;  2 ; 0
     ]
   *)
  let v1 = mk_vector [2 ; 1 ; 0 ; 0] in
  let v2 = mk_vector [0 ; 1 ; 2 ; 0] in
  lattice_of [v1 ; v2]

let proj_1_01 =
  IntLattice.hermitize (IntLattice.project ~keep:(fun dim -> dim <= 1) lattice1)

let proj_2_0 =
  IntLattice.hermitize (IntLattice.project ~keep:(fun dim -> dim <= 0) lattice2)

let sum_projected_12_in_23 =
  (* [ 2 ; 1 ] ; [ 1 ; 2 ] --> [ 1 ; 2 ] ; [ 0 ; -3 ] *)
  let proj_1_23 = IntLattice.project ~keep:(fun dim -> 2 <= dim && dim <= 3) lattice1 in
  let proj_2_23 = IntLattice.project ~keep:(fun dim -> 2 <= dim && dim <= 3) lattice2 in
  IntLattice.sum proj_1_23 proj_2_23

let test_hnf () =
  (* Generators are returned in no particular order *)
  let assert_same_generators actual expected =
    let sort = List.sort V.compare in
    List.iter2 assert_equal_qqvector (sort expected) (sort actual)
  in
  let expected_basis1 = [ [1 ; 2 ; 0 ; 0] ; [0 ; 0 ; 1 ; 0] ; [0 ; 0 ; 0 ; 1] ]
                        |> List.map mk_vector in
  assert_same_generators (IntLattice.generators lattice1) expected_basis1;
  let expected_basis2 = [ [2 ; 0 ; -2 ; 0] ; [0 ; 1 ; 2 ; 0] ]
                        |> List.map mk_vector in
  assert_same_generators (IntLattice.generators lattice2) expected_basis2

let test_member () =
  let v1 = mk_vector [ 2 ; 4 ; 6 ; 0] in
  let v2 = mk_vector [ 2 ; 1 ; 0 ; 0] in
  assert_equal (IntLattice.member v1 lattice1) true;
  assert_equal (IntLattice.member v1 lattice2) true;
  assert_equal (IntLattice.member v2 lattice1) false;
  assert_equal (IntLattice.member v2 lattice2) true

let test_project () =
  (* [project] is the image of the lattice under a coordinate projection.
     (mk_vector reverses its argument, so the last entry is dimension 0.) *)
  let equal_lattice l1 l2 =
    IntLattice.equal (IntLattice.hermitize l1) (IntLattice.hermitize l2)
  in
  assert_equal (IntLattice.subset proj_2_0 empty_lattice) true;
  assert_equal (equal_lattice proj_1_01 xy_lattice) true;
  (* lattice1 = < e0, e1, 2e2 + e3 >, so its image on dimension 2 is < 2e2 > *)
  let proj_1_2 = IntLattice.project ~keep:(fun dim -> dim = 2) lattice1 in
  assert_equal (equal_lattice proj_1_2 (lattice_of [mk_vector [0 ; 2 ; 0 ; 0]])) true;
  (* lattice2 = < 2e3 + e2, e2 + 2e1 >, so its image on dimensions 2, 3 is
     < 2e3 + e2, e2 > = < 2e3, e2 > *)
  let proj_2_23 = IntLattice.project ~keep:(fun dim -> 2 <= dim && dim <= 3) lattice2 in
  let expected = lattice_of [mk_vector [2 ; 0 ; 0 ; 0] ; mk_vector [0 ; 1 ; 0 ; 0]] in
  assert_equal (equal_lattice proj_2_23 expected) true

let test_project_as_dual () =
  (* [project_as_dual] is the intersection with the span of the kept
     dimensions. *)
  (* lattice1 = < e0, e1, 2e2 + e3 > *)
  let dual_1_2 = IntLattice.project_as_dual ~keep:(fun dim -> dim = 2) lattice1 in
  assert_equal (IntLattice.equal dual_1_2 empty_lattice) true;
  let dual_1_01 = IntLattice.project_as_dual ~keep:(fun dim -> dim <= 1) lattice1 in
  assert_equal (IntLattice.equal dual_1_01 xy_lattice) true;
  let dual_1_23 =
    IntLattice.project_as_dual ~keep:(fun dim -> 2 <= dim && dim <= 3) lattice1
  in
  assert_equal
    (IntLattice.equal dual_1_23 (lattice_of [mk_vector [1 ; 2 ; 0 ; 0]])) true;
  (* lattice2 = < 2e3 + e2, e2 + 2e1 >; the vectors in lattice2 that are
     independent of dimension 2 are generated by 2e3 - 2e1 *)
  let dual_2_013 = IntLattice.project_as_dual ~keep:(fun dim -> dim <> 2) lattice2 in
  assert_equal
    (IntLattice.equal dual_2_013 (lattice_of [mk_vector [2 ; 0 ; -2 ; 0]])) true

let test_intersect () =
  (* [ 1 ; 2 ; 0 ; 0
       0 ; 0 ; 1 ; 0
       0 ; 0 ; 0 ; 1 ]
     intersect with
     [ 2 ; 0 ; -2 ; 0
       0 ; 1 ;  2 ; 0
     ]

     [ 1 ;  2 ;  0 ; 0 ; 0 ; 0 ;  0 ; 0
       0 ;  0 ;  1 ; 0 ; 0 ; 0 ;  0 ; 0
       0 ;  0 ;  0 ; 1 ; 0 ; 0 ;  0 ; 0
      -2 ;  0 ;  2 ; 0 ; 2 ; 0 ; -2 ; 0
       0 ; -1 ; -2 ; 0 ; 0 ; 1 ;  2 ; 0
     ]
     ->
     [ 1 ;  2 ;  0 ; 0 ; 0 ; 0 ;  0 ; 0
       0 ;  0 ;  1 ; 0 ; 0 ; 0 ;  0 ; 0
       0 ;  0 ;  0 ; 1 ; 0 ; 0 ;  0 ; 0
       0 ;  4 ;  2 ; 0 ; 2 ; 0 ; -2 ; 0
       0 ; -1 ; -2 ; 0 ; 0 ; 1 ;  2 ; 0
     ]
     ->
     [ 1 ; 2 ; 0 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 0 ; 1 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 0 ; 0 ; 1 ; 0 ;  0 ;  0 ; 0
       0 ; 4 ; 2 ; 0 ; 2 ;  0 ; -2 ; 0
       0 ; 1 ; 2 ; 0 ; 0 ; -1 ; -2 ; 0
     ]
     ->
     [ 1 ; 2 ; 0 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 1 ; 2 ; 0 ; 0 ; -1 ; -2 ; 0
       0 ; 0 ; 0 ; 1 ; 0 ;  0 ;  0 ; 0
       0 ; 4 ; 2 ; 0 ; 2 ;  0 ; -2 ; 0
       0 ; 0 ; 1 ; 0 ; 0 ;  0 ;  0 ; 0
     ]
     ->
     [ 1 ; 2 ;  0 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 1 ;  2 ; 0 ; 0 ; -1 ; -2 ; 0
       0 ; 0 ;  0 ; 1 ; 0 ;  0 ;  0 ; 0
       0 ; 0 ; -6 ; 0 ; 2 ;  4 ;  6 ; 0
       0 ; 0 ;  1 ; 0 ; 0 ;  0 ;  0 ; 0
     ]
     ->
     [ 1 ; 2 ;  0 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 1 ;  2 ; 0 ; 0 ; -1 ; -2 ; 0
       0 ; 0 ;  0 ; 1 ; 0 ;  0 ;  0 ; 0
       0 ; 0 ;  1 ; 0 ; 0 ;  0 ;  0 ; 0
       0 ; 0 ;  0 ; 0 ; 2 ;  4 ;  6 ; 0
     ]
     Hence, the intersection is generated by [2 ; 4 ; 6 ; 0].
   *)
  let intersection = IntLattice.intersect lattice1 lattice2 in
  let expected = lattice_of [mk_vector [2 ; 4 ; 6 ; 0]] in
  assert_equal (IntLattice.subset intersection expected) true;
  assert_equal (IntLattice.subset expected intersection) true

let test_sum () =
  let lat1 = lattice_of [mk_vector [1 ; 2]] in
  let lat2 = lattice_of [mk_vector [-2 ; -5]] in
  let sum = IntLattice.sum lat1 lat2 in
  assert_equal (IntLattice.subset sum xy_lattice) true;
  assert_equal (IntLattice.subset xy_lattice (IntLattice.hermitize sum)) true

let suite = "IntLattice" >::: [
      "test_hnf" >:: test_hnf
    ; "test_member" >:: test_member
    ; "test_project" >:: test_project
    ; "test_project_as_dual" >:: test_project_as_dual
    ; "test_intersect" >:: test_intersect
    ; "test_sum" >:: test_sum
    ]
